<?php

/**
 * hook_libraries_info() implementation for the jssip library module
 *
 * JsSIP is a JavaScript implementation of Session Initiation Protocol
 * (SIP) from RFC 3261, a popular protocol for Internet-based
 * voice, video, chat, desktop sharing and other real-time protocols.
 *
 * Please download the JsSIP JavaScript source file to the directory
 *
 *   $(DRUPAL_HOME)/libraries/jssip/JsSIP.js
 *
 * and manually create a VERSION file corresponding to the version
 * in use, for example:
 *
 *   echo 1.0.0 > $(DRUPAL_HOME)/libraries/jssip/VERSION
 *
 * The JsSIP module is currently known to be used by version 7.x-2.x
 * of the DruCall module - see http://drucall.org for source code
 * and a live demonstration.
 *
 * @return
 *  An associative array whose keys are internal names of libraries
 *  and whose values are describing each library.
 */
function jssip_libraries_info() {
  $libraries['jssip'] = array(
    'name' => 'JsSIP',
    'vendor url' => 'http://jssip.net',
    'download url' => 'http://jssip.net/download/',
    'version arguments' => array(
      'file' => 'VERSION',
      'pattern' => '@([0-9\.]+)@',
      'lines' => 1,
      'cols' => 8,
    ),
    'files' => array(
          'js' => array(
            'JsSIP.js',
      ),
    ),
  );
  return $libraries;
}


